import { Montserrat } from "next/font/google";
import "./globals.css";
import { ReduxProvider } from "@/redux/providers";
import { Toaster } from "sonner";

// Import Montserrat
const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat", // define a CSS variable
  display: "swap", // good for performance
});

export const metadata = {
  title: "SpareGo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} font-sans antialiased`}>
        <ReduxProvider>
          {children}
          <Toaster position="top-right" richColors />
        </ReduxProvider>
      </body>
    </html>
  );
}
