import { Jura } from "next/font/google";
import "./globals.css";
import { ReduxProvider } from "@/redux/providers";
import { Toaster } from "sonner";

// Import Montserrat
const jura = Jura({
  subsets: ["latin"],
  variable: "--font-jura", 
  display: "swap", 
});

export const metadata = {
  title: "SpareGo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${jura.variable} font-sans antialiased`}>
        <ReduxProvider>
          {children}
          <Toaster richColors position="top-right" />
        </ReduxProvider>
      </body>
    </html>
  );
}
